// <auto-generated />
using System;
using BMS_project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMS_project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208104103_AddProjectDocuments")]
    partial class AddProjectDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BMS_project.Models.Announcement", b =>
                {
                    b.Property<int>("Announcement_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Announcement_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Announcement_ID"));

                    b.Property<DateTime>("Date_Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Date_Created");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Title");

                    b.Property<int>("User_ID")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("Announcement_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("announcement", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.Barangay", b =>
                {
                    b.Property<int>("Barangay_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Barangay_ID"));

                    b.Property<string>("Barangay_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Barangay_ID");

                    b.ToTable("barangay", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.Budget", b =>
                {
                    b.Property<int>("Budget_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Budget_ID"));

                    b.Property<int>("Barangay_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Term_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("budget")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("disbursed")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Budget_ID");

                    b.HasIndex("Barangay_ID");

                    b.ToTable("budget", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.Compliance", b =>
                {
                    b.Property<int>("Compliance_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("com_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Compliance_ID"));

                    b.Property<int?>("Barangay_ID")
                        .HasColumnType("int")
                        .HasColumnName("Barangay_id");

                    b.Property<DateTime?>("Date_Submitted")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Date_Submitted");

                    b.Property<DateTime>("Due_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<int?>("File_ID")
                        .HasColumnType("int")
                        .HasColumnName("File_ID");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsArchived");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status");

                    b.Property<int?>("TemplateFile_ID")
                        .HasColumnType("int")
                        .HasColumnName("TemplateFile_ID");

                    b.Property<int>("Term_ID")
                        .HasColumnType("int")
                        .HasColumnName("Term_ID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Type");

                    b.HasKey("Compliance_ID");

                    b.HasIndex("Barangay_ID");

                    b.HasIndex("File_ID");

                    b.HasIndex("TemplateFile_ID");

                    b.HasIndex("Term_ID");

                    b.ToTable("compliance", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.ComplianceDocument", b =>
                {
                    b.Property<int>("Document_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Document_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Document_ID"));

                    b.Property<int>("Compliance_ID")
                        .HasColumnType("int")
                        .HasColumnName("Compliance_ID");

                    b.Property<DateTime>("Date_Submitted")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Date_Submitted");

                    b.Property<int>("File_ID")
                        .HasColumnType("int")
                        .HasColumnName("File_ID");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("Remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status");

                    b.HasKey("Document_ID");

                    b.HasIndex("Compliance_ID");

                    b.HasIndex("File_ID");

                    b.ToTable("compliance_document", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.FederationFund", b =>
                {
                    b.Property<int>("Fund_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Fund_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Fund_ID"));

                    b.Property<decimal>("Allocated_To_Barangays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Allocated_To_Barangays");

                    b.Property<int>("Term_ID")
                        .HasColumnType("int")
                        .HasColumnName("Term_ID");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Total_Amount");

                    b.HasKey("Fund_ID");

                    b.HasIndex("Term_ID");

                    b.ToTable("federation_fund", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.FileUpload", b =>
                {
                    b.Property<int>("File_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("File_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("File_ID"));

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("File");

                    b.Property<string>("File_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("File_Name");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Timestamp");

                    b.Property<int?>("User_ID")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("File_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("file_upload", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.KabataanServiceRecord", b =>
                {
                    b.Property<int>("Record_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Record_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Record_ID"));

                    b.Property<DateTime?>("Actual_End_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Actual_End_Date");

                    b.Property<int>("Role_ID")
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.Property<int?>("Term_ID")
                        .HasColumnType("int")
                        .HasColumnName("Term_ID");

                    b.Property<int>("User_ID")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("Record_ID");

                    b.HasIndex("Role_ID");

                    b.HasIndex("Term_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("kabataan_service_record", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.KabataanTermPeriod", b =>
                {
                    b.Property<int>("Term_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Term_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Term_ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("Official_End_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Official_End_Date");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Start_Date");

                    b.Property<string>("Term_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Term_Name");

                    b.HasKey("Term_ID");

                    b.ToTable("kabataan_term_period", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("Role_ID")
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    b.Property<int?>("User_ID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Role_ID");

                    b.HasIndex("User_ID")
                        .IsUnique();

                    b.ToTable("login", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.Project", b =>
                {
                    b.Property<int>("Project_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Project_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Project_ID"));

                    b.Property<DateTime?>("Date_Submitted")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Date_Submitted");

                    b.Property<DateTime?>("End_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("End_Date");

                    b.Property<decimal>("Estimated_Cost")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Estimated_Cost");

                    b.Property<int>("File_ID")
                        .HasColumnType("int")
                        .HasColumnName("File_ID");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsArchived");

                    b.Property<string>("Project_Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Project_Description");

                    b.Property<string>("Project_Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Project_Status");

                    b.Property<string>("Project_Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Project_Title");

                    b.Property<DateTime?>("Start_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Start_Date");

                    b.Property<int?>("Term_ID")
                        .HasColumnType("int")
                        .HasColumnName("Term_ID");

                    b.Property<int?>("User_ID")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("Project_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.ProjectAllocation", b =>
                {
                    b.Property<int>("Allocation_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Allocation_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Allocation_ID"));

                    b.Property<decimal>("Amount_Allocated")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Amount_Allocated");

                    b.Property<int>("Budget_ID")
                        .HasColumnType("int")
                        .HasColumnName("Budget_ID");

                    b.Property<int>("Project_ID")
                        .HasColumnType("int")
                        .HasColumnName("Project_ID");

                    b.HasKey("Allocation_ID");

                    b.HasIndex("Budget_ID");

                    b.HasIndex("Project_ID");

                    b.ToTable("project_allocation", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.ProjectDocument", b =>
                {
                    b.Property<int>("Document_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Document_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Document_ID"));

                    b.Property<DateTime>("Date_Added")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Date_Added");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<int>("File_ID")
                        .HasColumnType("int")
                        .HasColumnName("File_ID");

                    b.Property<int>("Project_ID")
                        .HasColumnType("int")
                        .HasColumnName("Project_ID");

                    b.HasKey("Document_ID");

                    b.HasIndex("File_ID");

                    b.HasIndex("Project_ID");

                    b.ToTable("project_document", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.ProjectLog", b =>
                {
                    b.Property<int>("Log_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Log_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Log_ID"));

                    b.Property<DateTime?>("Changed_On")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Changed_On");

                    b.Property<int?>("Project_ID")
                        .HasColumnType("int")
                        .HasColumnName("Project_ID");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.Property<int?>("User_ID")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("Log_ID");

                    b.HasIndex("Project_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("project_log", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.Sitio", b =>
                {
                    b.Property<int>("Sitio_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sitio_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Sitio_ID"));

                    b.Property<int>("Barangay_ID")
                        .HasColumnType("int")
                        .HasColumnName("Barangay_id");

                    b.Property<string>("Sitio_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.HasKey("Sitio_ID");

                    b.HasIndex("Barangay_ID");

                    b.ToTable("sitio", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.SystemLog", b =>
                {
                    b.Property<int>("SysLog_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SysLog_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SysLog_id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Action");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DateTime");

                    b.Property<int?>("Record_ID")
                        .HasColumnType("int")
                        .HasColumnName("Record_ID");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasColumnName("Remark");

                    b.Property<string>("Table_Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Table_Name");

                    b.Property<int>("User_ID")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("SysLog_id");

                    b.HasIndex("User_ID");

                    b.ToTable("system_log", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<int?>("Barangay_ID")
                        .HasColumnType("int")
                        .HasColumnName("Barangay_ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("First_Name");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsArchived");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Last_Name");

                    b.Property<int?>("Role_ID")
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    b.HasKey("User_ID");

                    b.HasIndex("Barangay_ID");

                    b.HasIndex("Role_ID");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.YouthMember", b =>
                {
                    b.Property<int>("Member_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Member_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Member_ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<int?>("Barangay_ID")
                        .HasColumnType("int")
                        .HasColumnName("Barangay_ID");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Birthday");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsArchived");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Last_Name");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Sex");

                    b.Property<int?>("Sitio_ID")
                        .HasColumnType("int")
                        .HasColumnName("sitio_id");

                    b.HasKey("Member_ID");

                    b.HasIndex("Sitio_ID");

                    b.ToTable("youth_member", (string)null);
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<int>("Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Role_ID"));

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Role_Name");

                    b.HasKey("Role_ID");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("BMS_project.Models.Announcement", b =>
                {
                    b.HasOne("BMS_project.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BMS_project.Models.Budget", b =>
                {
                    b.HasOne("BMS_project.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("Barangay_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barangay");
                });

            modelBuilder.Entity("BMS_project.Models.Compliance", b =>
                {
                    b.HasOne("BMS_project.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("Barangay_ID");

                    b.HasOne("BMS_project.Models.FileUpload", "SubmissionFile")
                        .WithMany()
                        .HasForeignKey("File_ID");

                    b.HasOne("BMS_project.Models.FileUpload", "TemplateFile")
                        .WithMany()
                        .HasForeignKey("TemplateFile_ID");

                    b.HasOne("BMS_project.Models.KabataanTermPeriod", "KabataanTermPeriod")
                        .WithMany()
                        .HasForeignKey("Term_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_term_id");

                    b.Navigation("Barangay");

                    b.Navigation("KabataanTermPeriod");

                    b.Navigation("SubmissionFile");

                    b.Navigation("TemplateFile");
                });

            modelBuilder.Entity("BMS_project.Models.ComplianceDocument", b =>
                {
                    b.HasOne("BMS_project.Models.Compliance", "Compliance")
                        .WithMany("Documents")
                        .HasForeignKey("Compliance_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_project.Models.FileUpload", "File")
                        .WithMany()
                        .HasForeignKey("File_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compliance");

                    b.Navigation("File");
                });

            modelBuilder.Entity("BMS_project.Models.FederationFund", b =>
                {
                    b.HasOne("BMS_project.Models.KabataanTermPeriod", "Term")
                        .WithMany()
                        .HasForeignKey("Term_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Term");
                });

            modelBuilder.Entity("BMS_project.Models.FileUpload", b =>
                {
                    b.HasOne("BMS_project.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BMS_project.Models.KabataanServiceRecord", b =>
                {
                    b.HasOne("Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_project.Models.KabataanTermPeriod", "KabataanTermPeriod")
                        .WithMany()
                        .HasForeignKey("Term_ID");

                    b.HasOne("BMS_project.Models.User", "User")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KabataanTermPeriod");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BMS_project.Models.Login", b =>
                {
                    b.HasOne("Role", "Role")
                        .WithMany("Login")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_login_role");

                    b.HasOne("BMS_project.Models.User", "User")
                        .WithOne("Login")
                        .HasForeignKey("BMS_project.Models.Login", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_login_user");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BMS_project.Models.Project", b =>
                {
                    b.HasOne("BMS_project.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BMS_project.Models.ProjectAllocation", b =>
                {
                    b.HasOne("BMS_project.Models.Budget", "Budget")
                        .WithMany()
                        .HasForeignKey("Budget_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_project.Models.Project", "Project")
                        .WithMany("Allocations")
                        .HasForeignKey("Project_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BMS_project.Models.ProjectDocument", b =>
                {
                    b.HasOne("BMS_project.Models.FileUpload", "File")
                        .WithMany()
                        .HasForeignKey("File_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_project.Models.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("Project_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BMS_project.Models.ProjectLog", b =>
                {
                    b.HasOne("BMS_project.Models.Project", "Project")
                        .WithMany("Logs")
                        .HasForeignKey("Project_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BMS_project.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BMS_project.Models.Sitio", b =>
                {
                    b.HasOne("BMS_project.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("Barangay_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barangay");
                });

            modelBuilder.Entity("BMS_project.Models.SystemLog", b =>
                {
                    b.HasOne("BMS_project.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_User_Id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BMS_project.Models.User", b =>
                {
                    b.HasOne("BMS_project.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("Barangay_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_role");

                    b.Navigation("Barangay");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BMS_project.Models.YouthMember", b =>
                {
                    b.HasOne("BMS_project.Models.Sitio", "Sitio")
                        .WithMany()
                        .HasForeignKey("Sitio_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("BMS_project.Models.Compliance", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BMS_project.Models.Project", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Documents");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("BMS_project.Models.User", b =>
                {
                    b.Navigation("Login")
                        .IsRequired();

                    b.Navigation("ServiceRecords");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Navigation("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
